### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by realduziy** [micartey/Cardinal-Anticheat#197] opened 2024-04-09 21:33 UTC
### Information

CAC still loads and works, but it spams the console with these errors, and it sends blocks of spaces as well.

https://prnt.sc/EtHpC3ZvGJCF

https://pastebin.com/vB3Y4m6N

### When does the bug occure?

When the server starts.

### Cardinal Version

4.2.0

### Spigot Version

Purpur 1.20.4

**Comment by micartey** [comment] 2024-04-10 04:48
Partly duplicate of https://github.com/micartey/Cardinal-Anticheat/issues/181

Can you please specify what blocks of space are supported to be?

**Comment by realduziy** [comment] 2024-04-10 22:31
as in the screenshot that I sent, it sends rows of spaces in console

**Comment by micartey** [comment] 2024-04-22 07:51
In that case, it is a duplicate of #181 and will be closed as such.
The exceptions are due to spigots “legacy support” - you can ignore it. It has no effect as it will fallback to load the classes normally

**Closed by micartey** 2024-04-22 07:51 UTC
Labels: Bug Report
